import Container from "@/components/Container"
import { AuthProviders } from "./providers"


export const metadata = {
  title: '화양교회 온라인 등록관리 | 화양교회',
  description: 'Generated by Next.js',
}

export default async function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProviders>
      <Container>
        <div className="py-12">
          <h2 className="text-3xl font-bold tracking-tight pb-6">Dashboard <span className="text-base">(PC전용)</span></h2>
          <section>
            {children}
          </section>
        </div>
      </Container>
    </AuthProviders>
  )
}
